[Service]
Host = "localhost"
Port = 49990
ConnectRetries = 3
HealthCheck = ""
Labels = []
OpenMsg = "device simple started"
ReadMaxLimit = 256
Timeout = 5000

[Registry]
Host = "localhost"
Port = 8500
CheckPath = "/api/v1/ping"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  name = "edgex-core-data"
  Host = "localhost"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  name = "edgex-core-metadata"
  Host = "localhost"
  Port = 48081
  Timeout = 50000

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
RemoteURL = ''
File = "./device-simple.log"

# internal schedule
[[schedules]]
name = "10sec-schedule"
cron = "*/10 * * * * *"

[[scheduleEvents]]
name = "readTemperature"
schedule = "10sec-schedule"
parameters = ""
  [scheduleEvents.Addressable]
  path = "GetCommandExecutor::JC.RR5.NAE9.ConfRoom.Padre.Island::temperature"

[[scheduleEvents]]
name = "readHumidity"
schedule = "10sec-schedule"
parameters = ""
  [scheduleEvents.Addressable]
  path = "GetCommandExecutor::JC.RR5.NAE9.ConfRoom.Padre.Island::humidity"

[[schedules]]
name = "5sec-schedule"
cron = "*/5 * * * * *"

[[scheduleEvents]]
name = "readVoltage"
schedule = "5sec-schedule"
parameters = ""
  [scheduleEvents.Addressable]
  path = "GetCommandExecutor::GS1-AC-Drive::voltage"